App:
    name: "monitoring-app"
    version: "1.0.0"
    env: "dev"
    tribe: "dpe"
probe:
    normalTimeout: 5
log:
    level: "info"
    format: "json"

APM:
    enabled: true
    host: "datadog-agent"
    port: 8126
    rate: 1