
version: '3'
services:
  monitoring-app:
    build:
      context: .
    depends_on:
      - otel-collector
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

  # OpenTelemetry Collector Service
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    depends_on:
      - jaeger
      # - apm-server
    ports:
      - 4317:4317  # gRPC for OTLP metrics, logs, and traces
      - 4318:4318  # HTTP for OTLP
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro   # Access to Docker socket
      - /proc/:/host/proc/:ro                         # Access to host process information
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro        # Access to cgroup data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # Access to container logs
    command: ["--config", "/etc/otel-collector-config.yaml"]
    privileged: true  # Grants the container additional permissions
    user: "0:0" 

  # Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200
      - 9300:9300

  # Kibana Service for Visualization
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=true

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268

volumes:
  esdata:
    driver: local
