version: '3'
services:
  monitoring-app:
    build:
      context: .
      args:
        - GITLAB_ID=${GIT_USERNAME}
        - GITLAB_TOKEN=${GIT_ACCESS_TOKEN}
    depends_on:
      - datadog-agent
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always


  datadog-agent:
    container_name: datadog-agent
    image: "gcr.io/datadoghq/agent:latest"
    ports:
      - 4317:4317
      - 4318:4318
      - 8126:8126
    pid: host
    environment:
      DD_API_KEY: 2a86dbc9621e5f74dcc025e7924f0dae
      DD_SITE: "us5.datadoghq.com"
      DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT: 0.0.0.0:4317
      # DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT: 0.0.0.0:4318  # Adding HTTP endpoint
      # DD_APM_ENABLED: true
      # DD_APM_NON_LOCAL_TRAFFIC: true
      # DD_SYSTEM_PROBE_ENABLED: true
      # DD_APM_RECEIVER_SOCKET: /opt/datadog/apm/inject/run/apm.socket
      # DD_DOGSTATSD_SOCKET: /opt/datadog/apm/inject/run/dsd.socket
      DD_LOGS_ENABLED: true
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: true
      DD_COLLECT_DOCKER_METRICS: true
      DD_DOCKER_LABELS_AS_TAGS: '{"com.docker.compose.service":"monitoring-app"}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 