receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include: ["/var/lib/docker/containers/*/*.log"]  # Path to the Docker log files
    start_at: end
    operators:
      # Step 1: Move the raw log into attributes.log
      - type: move
        from: body
        to: attributes.log

      # Step 2: First level JSON parsing of the initial attributes.log
      - type: json_parser
        field: attributes.log
  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    collection_interval: 10s

processors:
  batch:
    timeout: 10s

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
      
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

service:
  pipelines:
    metrics:
      receivers: [otlp, docker_stats]
      processors: [batch]
      exporters: [prometheusremotewrite]
      
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
      
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [loki]