probes:
  - operation: "get_ip"
    tribe: "dpe"
    ip: "https://api.ipify.org"
    interval: 5
    probe_config:
      method: "GET"
      authorization: null
      query:
        format: "json"
      headers:
        Content-Type: application/json
  - operation: "get_ip_info"
    tribe: "dpe"
    ip: "https://api.ipify.org"
    interval: 5
    probe_config:
      method: "GET"
      authorization: null
      query:
        format: "json"
      headers:
        Content-Type: application/json
  - operation: "check_service"
    tribe: "dpe"
    ip: "https://example.com/check"
    dependencies: ["get_ip", "get_ip_info"]
    interval: 4
    probe_config:
      method: "POST"
      authorization: null
      query:
        formatee: "{{get_ip_info.ip}}"
        coba: "lainnya"
      headers:
        Content-Type: application/json
        Authorization: "Bearer {{get_ip_info.ip}}"
      body: |
        {
          "ip": "{{get_ip.ip}}",
          "city": "{{get_ip_info.ip}}",
        }
