global:
  scrape_interval: 15s  # Default scrape interval for all targets

scrape_configs:
  # - job_name: 'otel-collector'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['otel-collector:8888']